openapi: 3.0.3
info:
  title: Sedeo
  description: ""
  version: 1.0.0
tags:
  - name: user
    description: All requests related to user
paths:

  /users/me:
    get:
      tags:
        - user
      summary: Fetch information about currently logged in user profile
      description: In response you will find information about user profile
      operationId: fetch-user-profile
      responses:
        '200':
          description: User profile fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '404':
          description: User was not found
        '409':
          description: Unexpected error occurred

  /users/friends:
    get:
      tags:
        - user
      summary: Fetch friends of a logged in user
      description: In response you will get friends of a logged in user
      operationId: fetch-user-friends
      responses:
        '200':
          description: User friends fetched successfully
          content:
            application/json:
              schema:
                properties:
                  friends:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserFriend'
        '409':
          description: Unexpected error occurred

  /users/friend-requests:
    get:
      tags:
        - user
      summary: Fetch friend requests of a logged in user
      description: In response you will get friend requests of a logged in user
      operationId: fetch-user-friend-requests
      responses:
        '200':
          description: User friend requests fetched successfully
          content:
            application/json:
              schema:
                properties:
                  friendRequests:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserFriend'
        '409':
          description: Unexpected error occurred

components:
  schemas:

    UserProfileResponse:
      properties:
        userId:
          type: string
          example: 3dc197b6-ec2a-41e1-a31a-cdd2cb169cf0
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        phoneNumber:
          type: string
          example: 512348561
        email:
          type: string
          example: john.doe@example.com
        accountBalance:
          type: number
          example: 25.15

    UserFriend:
      properties:
        userId:
          type: string
          example: 3dc197b6-ec2a-41e1-a31a-cdd2cb169cf0
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        phoneNumber:
          type: string
          example: 512348561
